version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Install Google Chrome Stable

      # Build and test your Maven project
      - run:
          name: Build and test
          command: |
            mvn -B -DskipTests clean package
            mvn test
workflows:
  sample:
    jobs:
      - build-and-test